# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='price_per_day',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
