# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_approved',
            field=models.NullBooleanField(),
        ),
    ]
