# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0002_auto_20170302_1023'),
        ('moddle', '0002_auto_20170302_0936'),
    ]

    operations = [
    ]
