# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import moddle.models


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0003_merge_20170307_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_picture',
            field=models.ImageField(blank=True, upload_to=moddle.models.get_user_image_folder),
        ),
    ]
