# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0008_auto_20170310_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='adults_bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='boys_bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='booking',
            name='bikeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moddle.Bike'),
        ),
        migrations.AddField(
            model_name='booking',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='moddle.UserProfile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='moddle.UserProfile'),
        ),
    ]
