# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import moddle.models


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0009_auto_20170310_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=moddle.models.get_user_image_folder),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_picture',
            field=models.ImageField(blank=True, upload_to=moddle.models.get_bike_image_folder),
        ),
    ]
