# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moddle', '0010_auto_20170311_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, default=55.87371280304047, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, default=-4.2924705147743225, null=True),
        ),
    ]
